# Generated by Django 4.1.3 on 2022-11-16 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Osoba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
        migrations.RenameField(
            model_name='osoba',
            old_name='Druzyna',
            new_name='druzyna',
        ),
        migrations.RenameField(
            model_name='osoba',
            old_name='Imie',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='osoba',
            old_name='Nazwisko',
            new_name='nazwisko',
        ),
        migrations.AddField(
            model_name='osoba',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
