# Generated by Django 4.1.2 on 2022-10-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja1', '0002_osoba_data_dodania_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('kraj', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['surname']},
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.IntegerField(choices=[(1, 'Styczen'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecien'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpien'), (9, 'Wrzesien'), (10, 'Pazdziernik'), (11, 'Listopad'), (12, 'Grudzien')]),
        ),
        migrations.AddField(
            model_name='osoba',
            name='Druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja1.druzyna'),
        ),
    ]
